// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dream from "../src/Dream.res.mjs";
import * as DreamExpress from "../src/DreamExpress.res.mjs";

DreamExpress.run(undefined, (async function (param, paramsOpt) {
        return Dream.html("Good morning!", undefined);
      }));

export {
  
}
/*  Not a pure module */
