// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dream from "../src/Dream.res.mjs";
import * as DreamExpress from "../src/DreamExpress.res.mjs";

DreamExpress.run(undefined, Dream.logger(async function (param) {
          return Dream.html("Good morning, world!", undefined);
        }));

export {
  
}
/*  Not a pure module */
