// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dream from "../src/Dream.res.mjs";
import * as DreamExpress from "../src/DreamExpress.res.mjs";

DreamExpress.run(undefined, Dream.router([
          Dream.get("/", (async function (param) {
                  return Dream.html("Good morning, world!", undefined);
                })),
          Dream.get("/echo/:word", (async function (param) {
                  return Dream.html("Good morning, world!", undefined);
                }))
        ]));

function filterEmptyStrings(arr) {
  return arr.filter(function (s) {
              return s !== "";
            });
}

export {
  filterEmptyStrings ,
}
/*  Not a pure module */
