// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dream from "../src/Dream.res.mjs";
import * as DreamExpress from "../src/DreamExpress.res.mjs";

DreamExpress.run(undefined, Dream.router([
          Dream.get("/", (async function (param) {
                  return Dream.html("Good morning, world!", undefined);
                })),
          Dream.get("/echo/:word", (async function (param) {
                  var name = param.urlParams[0];
                  return Dream.html(name, undefined);
                }))
        ]));

export {
  
}
/*  Not a pure module */
