// Generated by ReScript, PLEASE EDIT WITH CARE

import Express from "express";

function run(portOpt, handler) {
  var port = portOpt !== undefined ? portOpt : 8080;
  var app = Express();
  app.use(function (req, res, next) {
        handler(req).then(function (response) {
              var status = response.status;
              if (status !== undefined) {
                res.status(status);
              }
              var body = response.body;
              if (body !== undefined) {
                res.send(body);
              }
              var json = response.json;
              if (json !== undefined) {
                res.json(json);
              }
              next();
            });
      });
  return app.listen(port, (function (param) {
                console.log("Listening on http://localhost:" + String(port));
              }));
}

export {
  run ,
}
/* express Not a pure module */
