// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dream from "./Dream.res.mjs";
import Express from "express";

var app = Express();

var router = Dream.router([
      Dream.get("/", (function (param) {
              return Promise.resolve({
                          status: 200
                        });
            })),
      Dream.get("/foo", (function (param) {
              return Promise.resolve({
                          status: 200
                        });
            }))
    ]);

Dream.DreamExpress.run(8081, Dream.logger(router));

var port = 8081;

export {
  port ,
  app ,
  router ,
}
/* app Not a pure module */
