// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as PathToRegexp from "path-to-regexp";

function make(url) {
  var fn = PathToRegexp.match(url);
  return function (path) {
    var t = fn(path);
    if (t === false) {
      return ;
    } else {
      return Core__Option.map(t, (function (t) {
                    return t.params;
                  }));
    }
  };
}

export {
  make ,
}
/* path-to-regexp Not a pure module */
