// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PathToRegexp from "path-to-regexp";

function make(s) {
  var r = PathToRegexp.pathToRegexp(s);
  return function (path) {
    var t = r.exec(path);
    if (t === null || t === undefined) {
      return ;
    } else {
      return t.slice(1);
    }
  };
}

export {
  make ,
}
/* path-to-regexp Not a pure module */
